---
- name: Check General Mandatory Variables Are Defined
  ansible.builtin.assert:
    that:
      - provision_virtual_esxi_username is defined
      - provision_virtual_esxi_password is defined
      - provision_virtual_esxi_hostname is defined
      - provision_virtual_esxi_vm_names is defined
    quiet: true
    fail_msg: Variable must be set when using this role.

- name: Check If Hosts Exist
  community.vmware.vmware_guest_info:
    hostname: "{{ provision_virtual_esxi_hostname }}"
    username: "{{ provision_virtual_esxi_username }}"
    password: "{{ provision_virtual_esxi_password }}"
    datacenter: "{{ provision_virtual_esxi_datacenter | default('') }}"
    validate_certs: "{{ provision_virtual_esxi_validate_certs | default(omit) }}"
    name: "{{ _esxi_name }}"
  failed_when: false
  register: _esxi_host_check
  loop: "{{ provision_virtual_esxi_vm_names }}"
  loop_control:
    loop_var: _esxi_name

- name: Include New ESXi Hosts Tasks
  when: >-
    (_esxi_host_check.results | selectattr('instance', 'undefined') is any) or
    (_esxi_host_check.results | selectattr('instance', 'defined') | map(attribute='instance') is not all)
  block:
    - name: Check VM Mandatory Variables Are Defined
      ansible.builtin.assert:
        that:
          - provision_virtual_esxi_iso_path is defined
          - provision_virtual_esxi_networks is defined
        quiet: true
        fail_msg: Variable must be set when using this role.
    - name: Include New ESXi Hosts Tasks
      ansible.builtin.include_tasks: deploy_new_esxi_hosts.yml

- name: Power On The ESXi Hosts
  ansible.builtin.include_role:
    name: cloud.vmware_ops.provision_vm
  vars:
    provision_vm_hostname: "{{ provision_virtual_esxi_hostname }}"
    provision_vm_username: "{{ provision_virtual_esxi_username }}"
    provision_vm_password: "{{ provision_virtual_esxi_password }}"
    provision_vm_validate_certs: "{{ provision_virtual_esxi_validate_certs | default(omit) }}"
    provision_vm_cluster: "{{ provision_virtual_esxi_cluster | default(omit) }}"
    provision_vm_datacenter: "{{ provision_virtual_esxi_datacenter | default(omit) }}"
    provision_vm_folder: "{{ provision_virtual_esxi_folder | default(omit) }}"
    provision_vm_name: "{{ _esxi_name }}"
    provision_vm_state: poweredon
  loop: "{{ provision_virtual_esxi_vm_names }}"
  loop_control:
    loop_var: _esxi_name
