---
- name: Playbook To Add An ESXI Host To VCenter
  hosts: all
  gather_facts: False

  roles:
    - role: cloud.vmware_ops.vcenter_host_connection
      vars:
        vcenter_host_connection_state: present
